# Downstream file to call from one-a.yml
name: one-b

on:
  workflow_call:
    inputs:
      config-word:
        required: true
        type: string

  workflow_dispatch:
    inputs:
      config-phrase:
        required: true
        type: string

jobs:
  slurp:
    if: ${{ inputs.config-phrase }}
    runs-on: ubuntu-latest

    steps:
      - name: Run a one-line script
        run: echo Hello, ${{ inputs.config-word }}!

  online-slurp:
    if: ${{ inputs.config-phrase }}
    runs-on: ubuntu-latest

    steps:
      - name: Run a one-line script
        run: echo Hello, ${{ inputs.config-phrase }}!
