# Downstream file to call from one-a.yml
name: one-b

on:
  workflow_call:
    inputs:
      config-word:
        required: true
        type: string

  workflow_dispatch:
    inputs:
      config-phrase:
        required: false
        type: string
        default: anteater

jobs:
  dump_contexts_to_log:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        id: github_context_step
        run: echo '${{ toJSON(github) }}'
      - name: Dump job context
        run: echo '${{ toJSON(job) }}'
      - name: Dump steps context
        run: echo '${{ toJSON(steps) }}'
      - name: Dump runner context
        run: echo '${{ toJSON(runner) }}'
      - name: Dump strategy context
        run: echo '${{ toJSON(strategy) }}'
      - name: Dump matrix context
        run: echo '${{ toJSON(matrix) }}'

  slurp:
    if: ${{ inputs.config-word }}
    runs-on: ubuntu-latest

    steps:
      - name: Run a one-line script
        run: echo Hello, ${{ inputs.config-word }}!

  online-slurp:
    if: ${{ github.event_name == workflow_dispatch }}
    runs-on: ubuntu-latest

    steps:
      - name: Run a one-line script
        run: echo Hello, ${{ inputs.config-phrase }}!
