# This is a workflow to mimic the structures we are investigating
# with correct access levels and packaging possibilities.

name: one-a

on:
  # Push is for use with basic file iteration
  push:
    branches: [ "main" ]
  # Pull request is the one we are most interested in
  pull_request:
    branches: '**'

jobs:
  build:
    # Given action, just nice as a reminder for now
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

  label-push:
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    steps:
      - name: Just a check
        run: echo I was a PR

  call-one-b:
    # One of three job triggers for the big file (one-b)
    uses: ./.github/workflows/one-b.yml
    with:
      config-word: moon
