name: one-one

on:
  workflow_run:
    workflows: ["zero-zero"]
    types:
      - completed

jobs:
  run-trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Link in one-one
        run: echo Hello, link!

      - name: again, but different
        uses: axodotdev/sarah-action@main
        with:
          event_name: ${{ github.event_name }}
