on: [push]

jobs:
  test_action_job:
    runs-on: ubuntu-latest
    name: A job to test the packaged action
    steps:
      - uses: actions/checkout@v3
      - id: beep-boop
        uses: axodotdev/sarah-action@v2
        with:
          who-to-greet: 'Mona the Octocat'
