on: [push]

jobs:
  test_action_job:
    runs-on: ubuntu-latest
    name: A job to test the packaged action
    steps:
      - name: I can access Github context
        run: echo '${{ toJSON(github) }}'
      - uses: actions/checkout@v3
      - id: beep-boop
        uses: axodotdev/sarah-action@main
          with:
            event_name: ${{ github.event_name }}
